### ISSUE TITLE
pythondrops do que se trata ?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [cleuton/pythondrops#1]
Eu sempre acompanho seu trabalho 40 anos de Desenvolvimento ao meu ver é uma grande referência, e como eu não sou um jovem burro, aprendo com quem sabe ! Gostaria de saber do que se trata esse projeto, grande abraço e muito obrigado  !

att.

**Comment by cleuton** [comment]
Dicas sobre a linguagem de programação python.

Em sex, 15 de jun de 2018 02:39, Junior <notifications@github.com> escreveu:
